"""
Tests for FITS loading and RMS estimation, using a synthetic CASA-style
FITS image generated by the ``synthetic_fits`` fixture.

The synthetic image has:
  - 512x512 pixels at 0.012 arcsec/pix
  - A Gaussian source at the center, peak ~5 mJy/beam
  - Gaussian noise with sigma = 10 uJy/beam (= 1e-5 Jy/beam)
  - Beam: BMAJ=0.12, BMIN=0.10 arcsec

CASA is not required for these tests.
"""
from __future__ import annotations

import math

import numpy as np
import pytest

from ajisai import (
    compute_image_stats,
    compute_rms,
    load_fits_image,
)


# ---------------------------------------------------------------------------
# load_fits_image
# ---------------------------------------------------------------------------
def test_load_fits_image_shape_and_metadata(synthetic_fits):
    img = load_fits_image(synthetic_fits)
    assert img["shape"] == (512, 512)
    assert img["cdelt_arcsec"] == pytest.approx(0.012, abs=1e-6)
    assert img["bmaj_arcsec"] == pytest.approx(0.12, abs=1e-6)
    assert img["bmin_arcsec"] == pytest.approx(0.10, abs=1e-6)
    # geometric mean beam in pixels: sqrt(0.12 * 0.10) / 0.012 = 9.128...
    assert img["beam_pix"] == pytest.approx(9.128, abs=0.01)
    # crpix is converted to 0-indexed
    assert img["crpix"] == (256, 256)


def test_load_fits_image_data_is_2d(synthetic_fits):
    """CASA exports as (1, 1, ny, nx); we squeeze to (ny, nx)."""
    img = load_fits_image(synthetic_fits)
    assert img["data2d"].ndim == 2
    assert img["data2d"].shape == (512, 512)


def test_load_fits_image_contains_source(synthetic_fits):
    """Peak should be near 5 mJy/beam, located near image center."""
    img = load_fits_image(synthetic_fits)
    data = img["data2d"]
    peak = np.nanmax(data)
    # source peak is 5e-3; with noise the apparent peak can be a touch higher
    assert 4.5e-3 < peak < 6e-3


def test_load_fits_image_coordinate_grids_have_correct_size(synthetic_fits):
    img = load_fits_image(synthetic_fits)
    assert img["x_arcsec"].shape == (512,)
    assert img["y_arcsec"].shape == (512,)


def test_load_fits_image_missing_file_raises(tmp_path):
    with pytest.raises(FileNotFoundError):
        load_fits_image(str(tmp_path / "does_not_exist.fits"))


# ---------------------------------------------------------------------------
# compute_rms - all methods recover noise on pure-noise image
# ---------------------------------------------------------------------------
TRUE_NOISE_JY = 1e-5  # 10 uJy/beam, set in conftest fixture


def test_rms_sigma_clip_on_noise_only(synthetic_fits_no_source):
    """sigma-clip recovers the true noise within 5% on a pure-noise image."""
    info = compute_rms(synthetic_fits_no_source, method="sigma_clip")
    assert info["rms"] == pytest.approx(TRUE_NOISE_JY, rel=0.05)
    assert info["method"] == "sigma_clip"


def test_rms_sigma_clip_excl_on_noise_only(synthetic_fits_no_source):
    """sigma_clip_excl matches sigma_clip on pure-noise (no source to exclude)."""
    info = compute_rms(synthetic_fits_no_source, method="sigma_clip_excl")
    assert info["rms"] == pytest.approx(TRUE_NOISE_JY, rel=0.05)


def test_rms_mad_on_noise_only(synthetic_fits_no_source):
    """MAD-based std also recovers the noise within 5%."""
    info = compute_rms(synthetic_fits_no_source, method="mad")
    assert info["rms"] == pytest.approx(TRUE_NOISE_JY, rel=0.05)


# ---------------------------------------------------------------------------
# compute_rms - source contamination handling
# ---------------------------------------------------------------------------
def test_rms_naive_overestimates_with_source(synthetic_fits):
    """The naive whole-image method is heavily biased upward by the source."""
    info = compute_rms(synthetic_fits, method="annulus", target_radius_arcsec=10)
    naive_std = np.nanstd(load_fits_image(synthetic_fits)["data2d"])
    # The naive std should be MUCH larger than the true noise on a source image
    assert naive_std > 5 * TRUE_NOISE_JY


def test_rms_sigma_clip_excl_with_source(synthetic_fits):
    """sigma_clip_excl should recover the noise even with a bright source.

    The source is at the center; center exclusion + sigma-clipping should
    bring the RMS estimate close to the true noise.
    """
    info = compute_rms(
        synthetic_fits,
        method="sigma_clip_excl",
        exclude_factor=5.0,
    )
    # Should be within 10% of the true noise
    assert info["rms"] == pytest.approx(TRUE_NOISE_JY, rel=0.10)
    assert info["method"] == "sigma_clip_excl"
    assert "justification" in info


def test_rms_methods_agree_on_noise_image(synthetic_fits_no_source):
    """All robust methods should agree to within 5% on pure noise."""
    methods = ["sigma_clip", "sigma_clip_excl", "mad"]
    rms_values = [compute_rms(synthetic_fits_no_source, method=m)["rms"] for m in methods]
    # Largest / smallest within 1.05
    assert max(rms_values) / min(rms_values) < 1.05


# ---------------------------------------------------------------------------
# compute_rms - input validation
# ---------------------------------------------------------------------------
def test_rms_annulus_requires_target_radius(synthetic_fits):
    """method='annulus' without target_radius_arcsec must raise."""
    with pytest.raises(ValueError, match="target_radius"):
        compute_rms(synthetic_fits, method="annulus")


def test_rms_unknown_method_raises(synthetic_fits):
    with pytest.raises(ValueError, match="Unknown RMS method"):
        compute_rms(synthetic_fits, method="some_fancy_method")


# ---------------------------------------------------------------------------
# compute_rms - justification dict contents
# ---------------------------------------------------------------------------
def test_rms_justification_records_method_parameters(synthetic_fits):
    info = compute_rms(synthetic_fits, method="sigma_clip_excl",
                       exclude_factor=4.0, sigma=3.0, maxiters=5)
    just = info["justification"]
    assert just["method"] == "sigma_clip_excl"
    assert just["sigma"] == 3.0
    assert just["maxiters"] == 5
    assert just["exclude_factor_beam"] == 4.0
    assert "description" in just


# ---------------------------------------------------------------------------
# compute_image_stats - integration of load + RMS + peak
# ---------------------------------------------------------------------------
def test_image_stats_returns_complete_dict(synthetic_fits):
    stats = compute_image_stats(synthetic_fits, rms_method="sigma_clip_excl")
    assert "peak_jy_beam" in stats
    assert "rms_jy_beam" in stats
    assert "snr" in stats
    assert "dynamic_range" in stats
    assert "bmaj_arcsec" in stats
    assert "bmin_arcsec" in stats


def test_image_stats_dynamic_range_is_sensible(synthetic_fits):
    """For a 5 mJy/bm source over 10 uJy/bm noise, DR should be ~500."""
    stats = compute_image_stats(synthetic_fits, rms_method="sigma_clip_excl")
    dr = stats["dynamic_range"]
    assert 300 < dr < 700


def test_image_stats_snr_equals_dr(synthetic_fits):
    """In the current implementation snr and dynamic_range are identical
    (peak / off-source RMS)."""
    stats = compute_image_stats(synthetic_fits, rms_method="sigma_clip_excl")
    assert stats["snr"] == pytest.approx(stats["dynamic_range"], rel=1e-9)


def test_image_stats_handles_noise_only(synthetic_fits_no_source):
    """A pure-noise image should give a low (~1-5) DR, not crash."""
    stats = compute_image_stats(synthetic_fits_no_source, rms_method="sigma_clip_excl")
    assert math.isfinite(stats["dynamic_range"])
    assert stats["dynamic_range"] < 20  # mostly random; certainly not 100+
